---
title: "Data Wrangling"
author: "Lisa"
date: "29/08/2019"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = TRUE, message = TRUE)
library(tidyverse) # loads packages for data manipulation (dplyr/tidyr)
```

## Resources

* [Data Wrangling](https://psyteachr.github.io/msc-data-skills/dplyr.html) in Data Skills for Reproducible Science
* [Data Transformation Cheatsheet](https://github.com/rstudio/cheatsheets/raw/master/data-transformation.pdf)
* [Stub script for this lesson](stubs/2_wrangling.Rmd)

## 6 Main Verbs

```{r}
# load the data
eye <- read_csv("data/eye_descriptions.csv")
```

### select()

```{r}
eye2 <- select(eye, user_id, user_id, `t1`)
head(eye2)

```

### filter()

```{r}
eye3 <- filter(eye, age >= 18, age < 40)

head(eye3)
range(eye3$age)
```

### arrange()

```{r}
eye4 <- arrange(eye3, sex, desc(age))

head(eye4)
```

### mutate()

```{r}
eye %>%
  filter(row_number() < 6) %>%
  select(user_id, sex, age) %>%
  mutate(year = 2019,
         age = round(age),
         birthyear = year - age,
         sex2 = recode(sex, "male" = "M", 
                            "female" = "F", 
                            .default = "X")
         )
```

### summarise()

```{r}
eye %>%
  mutate(age = ifelse(age > 100, NA, age)) %>%
  summarise(mean_age = mean(age, na.rm = TRUE),
          max_age = max(age, na.rm = TRUE))
```

### group_by()

```{r}
eye %>%
  mutate(age = ifelse(age > 100, NA, age)) %>%
  group_by(sex) %>%
  summarise(mean_age = mean(age, na.rm = TRUE),
          max_age = max(age, na.rm = TRUE))
```

## Additional Verbs


### rename()

```{r}
eye %>%
  filter(row_number() < 6) %>%
  rename(face1 = t1)
```

### distinct()

```{r}
tibble(
  x = c(1,1,2,2),
  y = c(1,1,2,3)
) %>%
  distinct()

```

### count()

```{r}
eye %>%
  mutate(age = round(age)) %>%
  count(sex, age)
```

### slice()

```{r}
eye %>%
  arrange(age) %>%
  group_by(sex) %>%
  slice(1:3)
```

### pull()

```{r}
age <- pull(eye, age)
```







